### ISSUE TITLE
Feature request: Add ability to run Lighthouse reports on logged in pages of app

### ISSUE THREAD

**Issue by drewrwilson** [netlify-labs/netlify-plugin-lighthouse#152]
**Is your feature request related to a problem? Please describe.**
I really like this plugin. One challenge is that most of my app is only available after login. I could have netlify run a lighthouse report on my `/login` page and my `/signup` pages but unless there is a mechanism to allow netlify to login or use some kind of token, I'm not able to use the plugin to run reports on most of my app. 

**Describe the solution you'd like**
I think there are a few ways it could solved. There could be an environmental variable for a session token or some mechanism to hit an endpoint with a username and password and get a session token so netlify could access post-login pages. Would it be possible to access environmental variables and include them in the config for the paths? if so, maybe I could store the session token in an environmental varibale in netlify and use it as a HTTP header when this plugin accesses a route.

**Describe alternatives you've considered**
Setting up puppeteer independent of this plugin to run a lighthouse report. I'd rather use this plugin because then it could trigger on each deploy

**Additional context**
Thank you for any thoughts! I originally posted a question about this on the netlify community board: https://community.netlify.com/t/lighthouse-plugin-reports-for-pages-that-require-login-to-my-app/31639/

**Comment by erezrokah** [comment]
Hi @drewrwilson thank you for opening this issue - this is a great use case.

So an example configuration would be:
```toml
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    path = "route1"
    custom_header = "NAME_OF_ENV_VARIABLE_IN_NETLIFY"
```
?

And the content of `NAME_OF_ENV_VARIABLE_IN_NETLIFY` would be `Authorization: whatever`?

We can also make `custom_header` an array of headers.

This matches option 3 here:
https://github.com/GoogleChrome/lighthouse/blob/master/docs/authenticated-pages.md#option-3-pass-custom-request-headers-with-lighthouse-cli

If need more advanced uses cases of cookie based auth we can follow up with option 1 from that document.

Would that work for you?

**Comment by drewrwilson** [comment]
Thank you for the thoughtful response, @erezrokah

Yes, what you are suggesting makes sense to me. Having an array of header variables as an option in the config that we could fill with environmental variables would solve my use case. It would allow me to use this plugin to generate Lighthouse reports on each Netlify deploy on pages in my app that require auth.

In my case, we use two header variables for auth: 
 * `X-Some-Session-Id: something` 
 * `X-Some-Token: something`

We do store these values in a cookie, but that's just to make sure that when a user comes back that we put them in the header. As long a they end up in the header of the request, the pages will load. Storing these two values in environment variables in Netlify will work in place of storing them in a cookie.

**Comment by erezrokah** [comment]
Hi @drewrwilson, sorry for just coming back to this now. I finally had the time to look at it.
The Lighthouse plugin serves a local version of the built site using a static http server and audits that site:
https://github.com/netlify-labs/netlify-plugin-lighthouse/blob/da409e03e28e93daf7be44074f7fa46f371f72de/src/index.js#L27

so I believe the post login pages should be available as long as they are generated as a part of the build process.

As for authentication, I'm not sure that would work even if we add an `Authorization` header as the static server won't know how to handle it.

If you can provide an example public repo with how you handle authentication that will help a lot to figure this out.

**Comment by kaganjd** [comment]
👋 We just got this exact question from an enterprise customer who'd like to run this plugin on every deploy. Their pages are behind an Auth0 login. If the plugin used the `onEnd` event instead of `onPostBuild`, and ran on a deployed site instead of on the files from a static server, do you think setting an auth header would work?

**Comment by erezrokah** [comment]
Hi @kaganjd, thanks for dropping by 👋 

Yes we could do that, probably with either an opt-in flag or a major version breaking change.
Also, please note that the plugin won't be able to fail the build from `onEnd` (or `onSuccess`).

Another option is to use `netlify dev` to simulate the prod environment.

If you can share an example repo so I can test my changes and verify they satisfy the customer's use case that will be great.

**Comment by drewrwilson** [comment]
Thanks for following up on this, @erezrokah! 

What @kaganjd suggested will work for my use-case too. 

I currently have it running on the deployed site by using an explicit url in the `netlify.toml` file (see below). It works for pages that don't require auth, but the report is always one version behind because the plugin is triggered before the site is done building & deploying. Using `onEnd` or `onSuccess` would solve this for me too.

Unfortunately I can't share access to my company's git repo, but I could do a call and pair on it and test. Let me know if you'd like to do that.

`netlify.toml`:
```
[[plugins]]
    package = "@netlify/plugin-lighthouse"
        [[plugins.inputs.audits]]
            url = "https://something.tech/login"
        [[plugins.inputs.audits]]
            url = "https://https://something.tech/signup"
```

PS @kaganjd cool to bump into a fellow public interest tech fellow in a github thread. small world! :) 🎉

**Comment by kaganjd** [comment]
@erezrokah that makes sense, thanks for laying it out. I'll touch base with the customer to see if we can get a sample repo 
@drewrwilson whatttt?! Small world indeed 🌏 Would love to hear what public interest tech things you're up to these days

**Comment by erezrokah** [comment]
@drewrwilson do you mind trying out a test branch? You can install it via `npm i -D "https://github.com/netlify-labs/netlify-plugin-lighthouse#feat/custom_headers"` and configure the headers via:

```toml
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.extra_headers]
Authorization = "one-token-to-rule-them-all"
[[plugins.inputs.audits]]
url = "https://something.tech/login"
[plugins.inputs.audits.extra_headers]
Authorization = "login token"
[[plugins.inputs.audits]]
url = "https://something.tech/signup"
[plugins.inputs.audits.extra_headers]
Authorization = "signup token"
```

**Comment by drewrwilson** [comment]
@erezrokah good idea! yes, I can test that branch with my code. In my case I have two headers variables that I use for authentication. they are in this format:
 `X-Something-Session-Id` : `some-uuid-goes-here`
 `X-Something-Token`: `somewildstring`

I looked through the code on that branch. I noticed it's using `Authentication` as the key for the headers. Is there a way for me to specify the key (to be `X-Something-Session-Id`)? eg Should I be specifying them as an environmental variables with a json object as the value?

**Comment by erezrokah** [comment]
Hi @drewrwilson you can use any key/value for the headers.
In you case it should be:
```toml
[[plugins]]
package = "@netlify/plugin-lighthouse"
[plugins.inputs.extra_headers]
X-Something-Session-Id = "some-uuid-goes-here"
X-Something-Token = "somewildstring"
[[plugins.inputs.audits]]
url = "https://something.tech/login"
```
